import Head from 'next/head'
import Navbar from '../components/Navbar'
import { table, minifyRecords} from './api/utils/Airtable'
import Todo from '../components/Todo';
import { TodosContext } from '../contexts/TodosContext'
import { useContext, useEffect } from 'react';
import auth0 from './api/utils/auth0';
import TodoForm from '../components/TodoForm';

export default function Home({initialTodos, user}) {
  const {todos, setTodos} = useContext(TodosContext);
  console.log(user)
  useEffect(()=>{
    console.log(initialTodos)
    setTodos(initialTodos);
  }, [])


  return (

    <div>
      {console.log(todos)}
      <Head>
        <title>Authentificated TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user}/>
      <main>
        {user ? (
            <>
              <TodoForm />
              <ul> 
                {
                  Array.isArray(todos) && todos.map(item => <Todo key={item.id} todo={item} />)
                }
              </ul>
            </>
        ) : (
            <p className="text-center mt-4">
                Please login to save todos!
            </p>
        )}
        
      </main>
      
      
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await auth0.getSession(context.req, context.res);
  let todos = [];
  if (session?.user) {
      todos = await table
          .select({ filterByFormula: `userId = '${session.user.sub}'` })
          .firstPage();
  }
  return {
      props: {
          initialTodos: minifyRecords(todos),
          user: session?.user || null,
      },
  };
}