import Head from 'next/head'
import Navbar from '../components/Navbar'
import { table, minifyRecords} from './api/utils/Airtable'
import Todo from '../components/Todo';
import { TodosContext } from '../contexts/TodosContext'
import { useContext, useEffect } from 'react';

export default function Home({initialTodos}) {
  const {todos, setTodos} = useContext(TodosContext);
  
  useEffect(()=>{
    console.log(initialTodos)
    setTodos(initialTodos);
  }, [])


  return (
    
    <div>
      <Head>
        <title>Authentificated TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <h1>Todo App</h1>
      </main>
     <ul> {
        Array.isArray(todos) && todos.map(item => <Todo key={item.id} todo={item} />)
      }</ul>
    </div>
  )
}

export async function getServerSideProps(context) {

  try {
    const todos = await table.select({}).firstPage();

    return {
        props: {
          
            initialTodos: minifyRecords(todos),
        },
    };
  } catch (error) {
    console.log(error)
  }
  
}